package models

import (
	"errors"

	_ "github.com/go-sql-driver/mysql"
	"github.com/sderohan/photo-gallery/hash"
	"github.com/sderohan/photo-gallery/rand"
	"golang.org/x/crypto/bcrypt"

	_ "github.com/jinzhu/gorm/dialects/mysql"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

var (
	//ErrorNotFound is returned when a resource a cannot be found in the database.
	ErrorNotFound = errors.New("models: resuource not found")

	// ErrInvalidID is returned when an invalid ID is provided
	// to a method like Delete
	ErrInvalidID = errors.New("models: ID provided was invalid")

	// ErrInvalidPassword is returned when an invalid password
	// is used during login
	ErrInvalidPassword = errors.New("mdels: incorrect password provided")
)

const userPwPepper = "secret-random-string"
const hmacSecretKey = "secret-hmac-key"

// // UserDB used to interact with the user database.
// //
// // If the user is found, we will return a nil error.
// // If the user is not found, we will return ErrNotFound
// // If there is another error, we will return an error with
// // more information about what went wrong. This may not be an error
// // generated by the models package.
// //
// // For a single user queries, any error but ErrNotFound should
// // probably result in a 500 error.
// type UserDB interface {
// 	// Methods for querying for single errors
// 	ByID(id uint) (*User, error)
// 	ByEmail(email string) (*User, error)
// 	ByRemember(token string) (*User, error)

// 	// Methods for altering users
// 	Create(user *User) error
// 	Update(user *User) error
// 	Delete(user *User) error

// 	// Used to close a DB connection
// 	Close() error

// 	// Migration helpers
// 	AutoMigrate() error
// 	DestructiveReset() error
// }

func NewUserService(connectionInfo string) (*UserService, error) {
	db, err := gorm.Open(mysql.Open(connectionInfo), &gorm.Config{})
	if err != nil {
		return nil, err
	}
	hmac := hash.NewHMAC(hmacSecretKey)
	return &UserService{
		db:   db,
		hmac: hmac,
	}, nil
}

type UserService struct {
	db   *gorm.DB
	hmac hash.HMAC
}

// ByID will look up a user with the provided ID.
// If the user is found, we will return a nil error.
// If the user is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong. This may not be an error
// generated by the models package.
//
// As a general rule, any error but ErrNotFound should
// probably result in a 500 error.
func (us *UserService) ByID(id uint) (*User, error) {
	var user User
	db := us.db.Where("id = ?", id)
	err := first(db, &user)
	return &user, err
}

// ByRemeber looks up a user with the given remeber token and
// returns that user. This method will handle hashing the token for us.
// Errors are the same as ByEmail
func (us *UserService) ByRemember(token string) (*User, error) {
	var user User
	rememberHash := us.hmac.Hash(token)
	err := first(us.db.Where("remember_hash = ?", rememberHash), &user)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// Returns the user info on given email address
func (us *UserService) ByEmail(email string) (*User, error) {
	var user User
	db := us.db.Where("email = ?", email)
	err := first(db, &user)
	return &user, err
}

// query using the provided gorm.DB and it will get the first item or errors if any
// if nothing is found in the query, it will return ErrorNotFound
func first(db *gorm.DB, dst interface{}) error {
	err := db.First(dst).Error
	if err == gorm.ErrRecordNotFound {
		return ErrorNotFound
	}
	return err
}

// Create will create the provided user and backfill data
func (us *UserService) Create(user *User) error {
	pwBytes := []byte(user.Password + userPwPepper)
	hashedBytes, error := bcrypt.GenerateFromPassword([]byte(pwBytes), bcrypt.DefaultCost)
	if error != nil {
		return error
	}
	user.PasswordHash = string(hashedBytes)
	user.Password = ""
	if user.Remember == "" {
		token, err := rand.RememberToken()
		if err != nil {
			return err
		}
		user.Remember = token
	}
	user.RememberHash = us.hmac.Hash(user.Remember)
	return us.db.Create(user).Error
}

// Update will update the provided user with all the data in the user object
func (us *UserService) Update(user *User) error {
	if user.Remember != "" {
		user.RememberHash = us.hmac.Hash(user.Remember)
	}
	return us.db.Save(user).Error
}

// Delete will delete the user with the provided ID
func (us *UserService) Delete(id uint) error {
	if id == 0 {
		return ErrInvalidID
	}
	user := User{Model: gorm.Model{ID: id}}
	return us.db.Delete(&user).Error
}

// drops the user table and rebuilds it
func (us *UserService) DestructiveReset() {
	err := us.db.Migrator().DropTable(&User{})
	if err != nil {
		panic(err)
	}
}

// AutoMigrate will attempt to automatically migrate the users table
func (us *UserService) AutoMigrate() error {
	if err := us.db.AutoMigrate(&User{}); err != nil {
		return err
	}
	return nil
}

// Authenticate can be used to authenticate a user with the provided email and password
func (us *UserService) Authenticate(email, password string) (*User, error) {
	// Check if current user exists
	foundUser, err := us.ByEmail(email)
	if err != nil {
		return nil, err
	}
	err = bcrypt.CompareHashAndPassword([]byte(foundUser.PasswordHash), []byte(password+userPwPepper))
	if err != nil {
		switch err {
		case bcrypt.ErrMismatchedHashAndPassword:
			return nil, ErrInvalidPassword
		default:
			return nil, err
		}
	}
	return foundUser, nil
}

// Close the database connection
func (us *UserService) Close() error {
	sqlDB, err := us.db.DB()
	if err != nil {
		return err
	}
	return sqlDB.Close()
}

type User struct {
	gorm.Model
	Name         string
	Email        string `gorm:"index;not null;unique"`
	Password     string `gorm:"-"`
	PasswordHash string `gorm:"not null"`
	Remember     string `gorm:"-"`
	RememberHash string `gorm:"not null;unique_index"`
}
